package model

// AuthTranEvent is the top-level Kafka event envelope for authentication transactions.
type AuthTranEvent struct {
	EventTimestamp string `json:"_event_timestamp"`
	EventID        string `json:"_event_id"`
	Category       string `json:"_category"`
	EventType      string `json:"_event_type"`
	Version        string `json:"_version"`
	Data           *Data  `json:"_data"`
}

type Data struct {
	AuthCode                         string  `json:"authCode"`
	SubRequestId                     float64 `json:"subRequestId"`
	Aua                              string  `json:"aua"`
	Sa                               string  `json:"sa"`
	Asa                              string  `json:"asa"`
	Ver                              string  `json:"ver"`
	Tid                              string  `json:"tid"`
	LicenseId                        string  `json:"licenseId"`
	ReqDateTime                      string  `json:"reqDateTime"`
	TknUsedFlag                      float64 `json:"tknUsedFlag"`
	TknType                          string  `json:"tknType"`
	PidTs                            string  `json:"pidTs"`
	PidVersion                       string  `json:"pidVersion"`
	PiUsesFlag                       float64 `json:"piUsesFlag"`
	PaUsesFlag                       float64 `json:"paUsesFlag"`
	PfaUsesFlag                      float64 `json:"pfaUsesFlag"`
	BioUsesFlag                      float64 `json:"bioUsesFlag"`
	BtFMRUsesFlag                    float64 `json:"btFMRUsesFlag"`
	BtFIRUsesFlag                    float64 `json:"btFIRUsesFlag"`
	BtIIRUsesFlag                    float64 `json:"btIIRUsesFlag"`
	PinUsesFlag                      float64 `json:"pinUsesFlag"`
	OtpUsesFlag                      float64 `json:"otpUsesFlag"`
	PiUsedFlag                       float64 `json:"piUsedFlag"`
	PaUsedFlag                       float64 `json:"paUsedFlag"`
	PfaUsedFlag                      float64 `json:"pfaUsedFlag"`
	BioUsedFlag                      float64 `json:"bioUsedFlag"`
	BtFMRUsedFlag                    float64 `json:"btFMRUsedFlag"`
	BtFIRUsedFlag                    float64 `json:"btFIRUsedFlag"`
	BtIIRUsedFlag                    float64 `json:"btIIRUsedFlag"`
	PinUsedFlag                      float64 `json:"pinUsedFlag"`
	OtpUsedFlag                      float64 `json:"otpUsedFlag"`
	OtpIdentifier                    string  `json:"otpIdentifier"`
	Lang                             string  `json:"lang"`
	PiNameUsedFlag                   float64 `json:"piNameUsedFlag"`
	PiMs                             string  `json:"piMs"`
	PiMv                             string  `json:"piMv"`
	PiMatchScore                     float64 `json:"piMatchScore"`
	PiLNameUsedFlag                  float64 `json:"piLNameUsedFlag"`
	PiLNameMs                        string  `json:"piLNameMs"`
	PiLNameMv                        string  `json:"piLNameMv"`
	PiLNameMatchScore                float64 `json:"piLNameMatchScore"`
	PiPhoneUsedFlag                  float64 `json:"piPhoneUsedFlag"`
	PiEmailUsedFlag                  float64 `json:"piEmailUsedFlag"`
	PiGenderUsedFlag                 float64 `json:"piGenderUsedFlag"`
	PiGender                         string  `json:"piGender"`
	PiDOBUsedFlag                    float64 `json:"piDOBUsedFlag"`
	PiDOB                            string  `json:"piDOB"`
	PiDOBTUsedFlag                   float64 `json:"pi_DOBTUsedFlag"`
	PiDOBT                           string  `json:"piDOBT"`
	PiAgeUsed_flag                   float64 `json:"piAgeUsed_flag"`
	PiAge                            string  `json:"piAge"`
	PfaAddressUsedFlag               float64 `json:"pfaAddressUsedFlag"`
	PfaAddressMs                     string  `json:"pfaAddressMs"`
	PfaAddressMv                     string  `json:"pfaAddressMv"`
	PfaMatchScore                    float64 `json:"pfaMatchScore"`
	PfaLaddrUsedFlag                 float64 `json:"pfaLaddrUsedFlag"`
	PfaLocalAddressMs                string  `json:"pfaLocalAddressMs"`
	PfaLocalAddressMv                string  `json:"pfaLocalAddressMv"`
	PfaLocalAddressMatcScore         float64 `json:"pfaLocalAddressMatcScore"`
	PaMs                             string  `json:"paMs"`
	PaCareOfUsedFlag                 float64 `json:"paCareOfUsedFlag"`
	PaHouseUsedFlag                  float64 `json:"paHouseUsedFlag"`
	PaStreetUsedFlag                 float64 `json:"paStreetUsedFlag"`
	PaLmUsedFlag                     float64 `json:"paLmUsedFlag"`
	PaLOCUsedFlag                    float64 `json:"paLOCUsedFlag"`
	PaVTCUsedFlag                    float64 `json:"paVTCUsedFlag"`
	PaVTC                            string  `json:"paVTC"`
	PaPOUsedFlag                     float64 `json:"paPOUsedFlag"`
	PaPO                             string  `json:"paPO"`
	PaSubDistrictUsedFlag            float64 `json:"paSubDistrictUsedFlag"`
	PaSubDistrict                    string  `json:"paSubDistrict"`
	PaDistrictUsedFlag               float64 `json:"paDistrictUsedFlag"`
	PaDistrict                       string  `json:"paDistrict"`
	PaStateUsedFlag                  float64 `json:"paStateUsedFlag"`
	PaState                          string  `json:"paState"`
	PaPCUsedFlag                     float64 `json:"paPCUsedFlag"`
	PaPC                             string  `json:"paPC"`
	FmrCount                         float64 `json:"fmrCount"`
	FirCount                         float64 `json:"firCount"`
	IirCount                         float64 `json:"iirCount"`
	FingerMatchScore                 float64 `json:"fingerMatchScore"`
	UidaiTFMR                        float64 `json:"uidaiTFMR"`
	AuaTFMR                          float64 `json:"auaTFMR"`
	FingerMatchThreshold             float64 `json:"fingerMatchThreshold"`
	FmrGalleryType                   string  `json:"fmrGalleryType"`
	FmrGalleryVendor                 string  `json:"fmrGalleryVendor"`
	FmrSDKVendor                     string  `json:"fmrSDKVendor"`
	FmrSDKVersion                    string  `json:"fmrSDKVersion"`
	FirGalleryType                   string  `json:"firGalleryType"`
	FirGalleryVendor                 string  `json:"firGalleryVendor"`
	FirSDKVendor                     string  `json:"firSDKVendor"`
	FirSDKVersion                    string  `json:"firSDKVersion"`
	IirGalleryType                   string  `json:"iirGalleryType"`
	IirGalleryVendor                 string  `json:"iirGalleryVendor"`
	IirSDKVendor                     string  `json:"iirSDKVendor"`
	IirSDKVersion                    string  `json:"iirSDKVersion"`
	AuthResult                       string  `json:"authResult"`
	ErrorCode                        string  `json:"errorCode"`
	ErrorClassification              string  `json:"errorClassification"`
	ResponseDateTime                 string  `json:"responseDateTime"`
	AuthDuration                     float64 `json:"authDuration"`
	Fdc                              string  `json:"fdc"`
	Idc                              string  `json:"idc"`
	Udc                              string  `json:"udc"`
	LocationLat                      string  `json:"locationLat"`
	LocationLong                     string  `json:"locationLong"`
	LocationVTCCode                  string  `json:"locationVTCCode"`
	LocationSubDistrictCode          string  `json:"locationSubDistrictCode"`
	LocationDistrictCode             string  `json:"locationDistrictCode"`
	LocationStateCode                string  `json:"locationStateCode"`
	LocationPC                       string  `json:"locationPC"`
	EnrolmentReferenceId             string  `json:"enrolmentReferenceId"`
	ResidentGender                   string  `json:"residentGender"`
	ResidentBirthDay                 float64 `json:"residentBirth_Day"`
	ResidentBirthMonth               float64 `json:"residentBirthMonth"`
	ResidentBirthYear                float64 `json:"residentBirthYear"`
	ResidentDOB                      string  `json:"residentDOB"`
	ResidentDOBT                     string  `json:"residentDOBT"`
	ResidentAge                      float64 `json:"residentAge"`
	ResidentPincode                  string  `json:"residentPincode"`
	ResidentVTCCode                  string  `json:"residentVTCCode"`
	ResidentVTCName                  string  `json:"residentVTCName"`
	ResidentPOName                   string  `json:"residentPOName"`
	ResidentSubDistrictCode          string  `json:"residentSubDistrictCode"`
	ResidentSubDistrictName          string  `json:"residentSubDistrictName"`
	ResidentDistrictCode             string  `json:"residentDistrictCode"`
	ResidentDistrictName             string  `json:"residentDistrictName"`
	ResidentStateCode                string  `json:"residentStateCode"`
	ResidentStateName                string  `json:"residentStateName"`
	UidGenerationDate                string  `json:"uidGenerationDate"`
	Txn                              string  `json:"txn"`
	AuthType                         string  `json:"authType"`
	HashUID                          string  `json:"hashUID"`
	LocationAlt                      string  `json:"locationAlt"`
	Lot                              string  `json:"lot"`
	BfdDoneFlag                      float64 `json:"bfdDoneFlag"`
	FingerMatchingType               string  `json:"fingerMatchingType"`
	FingerFusionPerfomed             float64 `json:"fingerFusionPerfomed"`
	IrisMatchScore                   float64 `json:"irisMatchScore"`
	IrisThreshold                    float64 `json:"irisThreshold"`
	IrisMatchingType                 string  `json:"irisMatchingType"`
	IrisFusionPerfomed               float64 `json:"irisFusionPerfomed"`
	AuthXMLSize                      float64 `json:"authXMLSize"`
	PidSize                          float64 `json:"pidSize"`
	DataType                         string  `json:"dataType"`
	SkeyScheme                       string  `json:"skeyScheme"`
	SskType                          string  `json:"sskType"`
	Ki                               string  `json:"ki"`
	KycFlag                          float64 `json:"kycFlag"`
	ActionCodes                      string  `json:"actionCodes"`
	RegisteredDeviceSoftwareId       string  `json:"registeredDeviceSoftwareId"`
	RegisteredDeviceSoftwareVersion  string  `json:"registeredDeviceSoftwareVersion"`
	DeviceProviderId                 string  `json:"deviceProviderId"`
	DeviceCode                       string  `json:"deviceCode"`
	ModelId                          string  `json:"modelId"`
	CertExpiryDate                   string  `json:"certExpiryDate"`
	SubErrorCode                     string  `json:"subErrorCode"`
	AuthenticationMode               string  `json:"authenticationMode"`
	FaceUses                         float64 `json:"faceUses"`
	FaceUsed                         float64 `json:"faceUsed"`
	FaceMatchScore                   float64 `json:"faceMatchScore"`
	FaceMatchThreshold               float64 `json:"faceMatchThreshold"`
	FaceMatchType                    string  `json:"faceMatchType"`
	FaceFusionDone                   float64 `json:"faceFusionDone"`
	FaceMultimodalityFusionScore     float64 `json:"faceMultimodalityFusionScore"`
	FaceMultimodalityFusionThreshold float64 `json:"faceMultimodalityFusionThreshold"`
	FaceSdkVendor                    string  `json:"faceSdkVendor"`
	FaceSdkVersion                   string  `json:"faceSdkVersion"`
	DeviceMetaData                   string  `json:"deviceMetaData"`
	DeepPrintGalleryType             string  `json:"deepPrintGalleryType"`
	DeepPrintGalleryVendor           string  `json:"deepPrintGalleryVendor"`
	DeepPrintSdkVendor               string  `json:"deepPrintSdkVendor"`
	DeepPrintSdkVersion              string  `json:"deepPrintSdkVersion"`
	DeepPrintMatchScoreFinger1       float64 `json:"deepPrintMatchScoreFinger1"`
	DeepPrintMatchScoreFinger2       float64 `json:"deepPrintMatchScoreFinger2"`
	DeepPrintMatchIsPerfomed         float64 `json:"deepPrintMatchIsPerfomed"`
	DeepPrintMatchResult             float64 `json:"deepPrintMatchResult"`
	ServerId                         string  `json:"serverId"`
}

// KafkaConfig holds the configuration needed to create a Kafka consumer.
type KafkaConfig struct {
	BootstrapServers []string
	GroupId          string
	AutoOffsetReset  string
}
